### ISSUE TITLE
Add Kibana connection information

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/docs#45]
Not sure if it makes sense to mirror the whole CONTRIBUTING.md, but I think it would be good to at least add the information under the [working with elasticsearch](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#working-with-elasticsearch) section, specifically regarding Kibana connections

**Comment by lamusmaser** [comment]
There are several areas here that might work better within the docs. I'll look into it with some of my planned technical reviews and refactoring.

**Comment by bbilly1** [comment]
I don't want to duplicate docs over multiple places like that. That makes it difficult to update.

The docs here are mostly user focused, as in how to install and how to use this project. While the main repo has developer focused instructions. So it makes sense to have the Kibana instructions with the dev instructions, as that is not really relevant for *regular* users.
