### ISSUE TITLE
installation in Docker instruction errors or not full

### ISSUE THREAD

**Issue by VitaliyAT** [tubearchivist/docs#46]
in this page:
_https://docs.tubearchivist.com/installation/synology/_
in line:
_10. In the Environment tab, add in any Redis specific environment variables that may apply (none by default)._
not clear what should be in variables, I write them as _none_:
![image](https://github.com/user-attachments/assets/5711620b-223e-431e-95a8-0db08e7f0e55)
and get:
![image](https://github.com/user-attachments/assets/5e6a9512-d69c-4faf-8842-0f1f7ad979dc)

Could you explain and renew\correct instruction for docker in Synology ?

**Comment by bbilly1** [comment]
None by default, means there are no additional environment variables needed by default, none.
