### ISSUE TITLE
Docs don't specify how to use `POST: /api/playlist/<playlist_id>/`

### ISSUE THREAD

**Issue by douglasg14b** [tubearchivist/docs#48]
It seems like this endpoint expects an object, but the docs do not appear to elaborate on what that is

![image](https://github.com/user-attachments/assets/827d9ddc-cfd3-4a37-af95-b2b98cee700b)

The endpoint appears to be here:

https://github.com/tubearchivist/tubearchivist/blob/cfe94c8dacca3b4f1f8d874d6ddf66553d6dcbd7/tubearchivist/api/views.py#L532C1-L557C75

```python

    def post(self, request, playlist_id):
        """post to custom playlist to add a video to list"""
        playlist = YoutubePlaylist(playlist_id)
        if not playlist.is_custom_playlist():
            message = f"playlist with ID {playlist_id} is not custom"
            return Response({"message": message}, status=400)

        action = request.data.get("action")
        if action not in self.valid_custom_actions:
            message = f"invalid action: {action}"
            return Response({"message": message}, status=400)

        video_id = request.data.get("video_id")
        if action == "create":
            playlist.add_video_to_playlist(video_id)
        else:
            hide = UserConfig(request.user.id).get_value("hide_watched")
            playlist.move_video(video_id, action, hide_watched=hide)

        return Response({"success": True}, status=status.HTTP_201_CREATED)
```

**Comment by douglasg14b** [comment]
Been trying to get this endpoint working for a bit, but I can't seem to get videos added to custom playlists 🤔 

```js
        const response = await fetch(`${TA_BASE_URL}/api/playlist/${PLAYLIST_ID}`, {
            method: 'POST',
            headers: {
                'Authorization': `Token ${TA_API_KEY}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                data: [{ action: 'create', video_id: videoId }]
            })
        });
```

This seems to trigger the `GET` endpoint, as the response returns metadata bout the playlist with a `200`, but not the response I'd expect from here: https://github.com/tubearchivist/tubearchivist/blob/cfe94c8dacca3b4f1f8d874d6ddf66553d6dcbd7/tubearchivist/api/views.py#L557

**Comment by douglasg14b** [comment]
Looks like the trialing `/` is required for these endpoints for some reason. Wonky routing?

**Comment by bbilly1** [comment]
added to the docs.
